# Generic default Joy Teleop velocity limits
teleop_twist_joy_node:
  ros__parameters:
    # Regular
    scale_linear.x: 1.0
    scale_linear.y: 1.0
    scale_angular.yaw: 1.0

    # Turbo
    scale_linear_turbo.x: 2.0
    scale_linear_turbo.y: 2.0
    scale_angular_turbo.yaw: 2.0
